"""Generate the vendored homoglyph table for `devloop.spec_phase._homoglyph_table`.

This is a one-shot build-time helper. We use the `confusable-homoglyphs` PyPI
package (which mirrors https://www.unicode.org/Public/security/latest/confusables.txt)
to extract a `{non_ascii_char: ascii_char}` map covering ALL Unicode
confusables that visually resemble the ASCII letters used in our forbidden
soft-language phrases.

The output is committed to the repo so production does NOT depend on
`confusable-homoglyphs` at runtime.

Usage:
    python scripts/generate_homoglyph_table.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

from confusable_homoglyphs import confusables

# ASCII letters that appear in our forbidden phrases (case-insensitive).
# Keep this in sync with `_FORBIDDEN_PHRASES_RE` in spec.py.
TARGET_LETTERS = set("abcdefghilmnopqrstuvwxy" + "ABCDEFGHILMNOPQRSTUVWXY")

# Script aliases we WHITELIST — characters in these scripts are NEVER folded
# to ASCII even if `confusable-homoglyphs` lists them as confusable. This
# protects legitimate multi-language spec text (Chinese 业务需求,
# Arabic النظام, Hebrew, Devanagari, ...) from being mangled into ASCII
# soft-language matches.
WHITELIST_ALIASES = {
    "HAN",
    "HIRAGANA",
    "KATAKANA",
    "HANGUL",
    "ARABIC",
    "HEBREW",
    "DEVANAGARI",
    "BENGALI",
    "GUJARATI",
    "GURMUKHI",
    "TAMIL",
    "TELUGU",
    "KANNADA",
    "MALAYALAM",
    "SINHALA",
    "THAI",
    "LAO",
    "MYANMAR",
    "KHMER",
    "TIBETAN",
    "GEORGIAN",
    "ETHIOPIC",
}


def _char_script_alias(c: str) -> str | None:
    """Return the script alias (e.g. ``CYRILLIC``) for a single char."""
    res = confusables.is_confusable(c, greedy=True)
    if res:
        return res[0].get("alias")
    return None


def main() -> int:
    data = confusables.confusables_data
    fold: dict[str, str] = {}

    for src_char, alts in data.items():
        if all(ord(ch) < 128 for ch in src_char):
            continue
        if len(src_char) != 1:
            continue
        cat = unicodedata.category(src_char)
        if cat.startswith("M"):
            continue

        src_alias = _char_script_alias(src_char)
        if src_alias in WHITELIST_ALIASES:
            continue

        ascii_target: str | None = None
        for alt in alts:
            cand = alt.get("c", "")
            cand_stripped = "".join(ch for ch in cand if ch not in ("\u200e", "\u200f"))
            if (
                len(cand_stripped) == 1
                and ord(cand_stripped) < 128
                and cand_stripped in TARGET_LETTERS
            ):
                ascii_target = cand_stripped
                break

        if ascii_target is None:
            continue

        fold[src_char] = ascii_target

    # Hand-augment with the canonical Cyrillic + Greek look-alikes so the
    # table is comprehensive even if the package's data omits a direction.
    cyrillic_extras = {
        "\u0430": "a",
        "\u0410": "A",
        "\u0435": "e",
        "\u0415": "E",
        "\u043e": "o",
        "\u041e": "O",
        "\u0440": "p",
        "\u0420": "P",
        "\u0441": "c",
        "\u0421": "C",
        "\u0443": "y",
        "\u0423": "Y",
        "\u0445": "x",
        "\u0425": "X",
        "\u0455": "s",
        "\u0405": "S",
        "\u0456": "i",
        "\u0406": "I",
        "\u0458": "j",
        "\u0408": "J",
        "\u0412": "B",
        "\u041d": "H",
        "\u041a": "K",
        "\u041c": "M",
        "\u0422": "T",
        "\u0454": "e",
        "\u04bb": "h",
    }
    greek_extras = {
        "\u03b1": "a",
        "\u0391": "A",
        "\u03b5": "e",
        "\u0395": "E",
        "\u03bf": "o",
        "\u039f": "O",
        "\u03c1": "p",
        "\u03a1": "P",
        "\u03bd": "v",
        "\u03c5": "u",
        "\u03a5": "Y",
        "\u03b9": "i",
        "\u0399": "I",
        "\u0392": "B",
        "\u0397": "H",
        "\u039a": "K",
        "\u039c": "M",
        "\u039d": "N",
        "\u03a4": "T",
        "\u03a7": "X",
        "\u0396": "Z",
        "\u03ba": "k",
    }
    for src, tgt in {**cyrillic_extras, **greek_extras}.items():
        if tgt in TARGET_LETTERS:
            fold[src] = tgt

    out_path = (
        Path(__file__).resolve().parents[1] / "devloop" / "spec_phase" / "_homoglyph_table.py"
    )
    lines = [
        '"""Vendored Unicode homoglyph -> ASCII fold table for A4 soft-language defense.',
        "",
        "Generated by ``scripts/generate_homoglyph_table.py`` from the",
        "``confusable-homoglyphs`` package (which mirrors",
        "https://www.unicode.org/Public/security/latest/confusables.txt).",
        "",
        "DO NOT EDIT BY HAND -- re-run the generator if you need updates.",
        "",
        "Whitelisted scripts (HAN, HIRAGANA, KATAKANA, HANGUL, ARABIC, HEBREW,",
        "DEVANAGARI, ...) are intentionally EXCLUDED -- legitimate multi-language",
        "spec text in those scripts must pass through unfolded.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# Map: Unicode confusable character -> equivalent ASCII letter.",
        "# Only NON-ASCII characters that resemble one of the ASCII letters used",
        "# in our forbidden soft-language phrases are present.",
        "HOMOGLYPH_TO_ASCII: dict[str, str] = {",
    ]
    for src in sorted(fold.keys()):
        tgt = fold[src]
        try:
            name = unicodedata.name(src)
        except ValueError:
            name = "UNKNOWN"
        if ord(src) <= 0xFFFF:
            esc = f"\\u{ord(src):04x}"
        else:
            esc = f"\\U{ord(src):08x}"
        lines.append(f'    "{esc}": "{tgt}",  # {name}')
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(fold)} entries to {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
