"""Adversarial drift tests for B1 (md/json roundtrip consistency).

Each test attacks one specific way the bridge could silently lose or invent
content during the spec → md → spec → md roundtrip:

1. Clean baseline (no monkey-patching) — assertion must pass.
2. spec_to_markdown injects an extra ``## ...`` section not backed by a
   Spec field — both ``find_md_only_content`` (which detects it) and
   ``assert_spec_roundtrip_consistent`` (which raises) must catch it.
3. spec_to_json silently drops the ``self_concerns`` list — assertion must
   raise with the field path included for human triage.
4. The writer's ``_Generated by_ ...`` footer must NOT cause a false
   positive in either function.
5. Unicode (emoji + CJK) in normative fields must survive the roundtrip
   byte-for-byte.
6. A spec with empty ``user_stories`` (and other optional sections empty)
   roundtrips cleanly.
"""

from __future__ import annotations

import pytest

from devloop.spec_phase import md_json_bridge
from devloop.spec_phase.md_json_bridge import (
    assert_spec_roundtrip_consistent,
    find_md_only_content,
    spec_to_json,
    spec_to_markdown,
)
from devloop.spec_phase.schemas import (
    AcceptanceScenario,
    CodeRef,
    Concern,
    EdgeCase,
    Entity,
    FunctionalRequirement,
    Priority,
    Spec,
    SpecMetadata,
    SuccessCriterion,
    UserStory,
)

# ---------------------------------------------------------------------------
# Helpers — keep each fixture spec tightly scoped so when an assertion fails
# the cause is obvious from the test name alone.
# ---------------------------------------------------------------------------


def _baseline_spec() -> Spec:
    """A non-trivial Spec exercising the majority of normative sections."""
    return Spec(
        metadata=SpecMetadata(
            feature_id="b1-drift",
            title="B1 Drift Adversarial",
            writer_model="claude",
            reviewer_model="gpt",
            iterations=2,
        ),
        summary="Detect roundtrip drift between markdown and json renderings.",
        user_stories=[
            UserStory(
                id="US-1",
                priority=Priority.P1,
                title="Validator catches dropped fields",
                description="A spec with a bug in the bridge raises on roundtrip.",
                acceptance=[
                    AcceptanceScenario(
                        given="a spec",
                        when="the bridge drops a field",
                        then="the assertion raises with the field name",
                    )
                ],
            )
        ],
        functional_requirements=[
            FunctionalRequirement(
                id="FR-001",
                text="The bridge must roundtrip every normative Spec field.",
                requirement_type="functional",
                code_references=[
                    CodeRef(
                        path="devloop/spec_phase/md_json_bridge.py",
                        symbols=["assert_spec_roundtrip_consistent"],
                    )
                ],
            ),
        ],
        success_criteria=[
            SuccessCriterion(
                id="SC-001",
                text="Drift in either direction raises ValueError with a diff.",
                metric="raises ValueError",
                threshold="100% of injected drift cases",
            )
        ],
        key_entities=[
            Entity(
                name="Spec",
                description="The structured specification model.",
            )
        ],
        edge_cases=[
            EdgeCase(
                description="Empty user_stories list",
                handling="rendered as no section; roundtrip clean",
            )
        ],
        assumptions=["pydantic preserves field order on dump"],
        out_of_scope=["fuzzing of unrelated yaml renderers"],
        self_concerns=[
            Concern(
                location="FR-001",
                concern="bridge may evolve faster than tests",
                evidence_gap="no contract test for new field additions",
            )
        ],
    )


# ---------------------------------------------------------------------------
# 1. Clean baseline
# ---------------------------------------------------------------------------


def test_roundtrip_passes_clean_spec() -> None:
    """A normal, well-formed Spec must roundtrip without raising and produce
    no spurious unmapped-section warnings."""
    spec = _baseline_spec()
    # Must not raise.
    assert_spec_roundtrip_consistent(spec)
    assert find_md_only_content(spec) == []


# ---------------------------------------------------------------------------
# 2. md-only injected section — must be caught by both APIs.
# ---------------------------------------------------------------------------


def test_roundtrip_catches_md_only_section(monkeypatch: pytest.MonkeyPatch) -> None:
    """If the markdown renderer emits an ``## ...`` section the Spec model
    doesn't know about, both defenses must fire:

    - ``find_md_only_content`` lists the unmapped heading (deterministic
      check based on the H2 section map).
    - ``assert_spec_roundtrip_consistent`` raises (byte-equality check on
      the round-tripped markdown — the second render won't carry the
      injected section).
    """
    spec = _baseline_spec()
    real_to_md = md_json_bridge.spec_to_markdown
    injected_heading = "Implementation Notes (Drift Injected)"

    # --- (a) ``find_md_only_content`` flank: drift fires on every call so
    # the H2-scanning helper sees the unmapped heading at least once.
    def always_drifting_to_md(spec_arg: Spec) -> str:
        base = real_to_md(spec_arg)
        return base + f"\n## {injected_heading}\n\nAuthor-only scratch.\n"

    monkeypatch.setattr(md_json_bridge, "spec_to_markdown", always_drifting_to_md)
    unmapped = find_md_only_content(spec)
    assert len(unmapped) == 1
    assert injected_heading in unmapped[0]
    assert "unknown" in unmapped[0].lower() or "no entry" in unmapped[0].lower()

    # --- (b) ``assert_spec_roundtrip_consistent`` flank: inject the extra
    # section only on the *first* render so the round-trip produces a
    # diverging second render — exactly the asymmetric drift the assertion
    # is meant to catch.
    call_count = {"n": 0}

    def first_call_only_drift(spec_arg: Spec) -> str:
        call_count["n"] += 1
        base = real_to_md(spec_arg)
        if call_count["n"] == 1:
            return base + f"\n## {injected_heading}\n\nAuthor-only scratch.\n"
        return base

    monkeypatch.setattr(md_json_bridge, "spec_to_markdown", first_call_only_drift)
    with pytest.raises(ValueError) as exc_info:
        assert_spec_roundtrip_consistent(spec)
    msg = str(exc_info.value)
    assert "markdown roundtrip differs" in msg
    # The error must localize the drift (line number + content) so a human
    # debugging the bridge can find it without spelunking through diff tools.
    assert "line=" in msg


# ---------------------------------------------------------------------------
# 3. json field drop — assertion must raise and name the dropped field.
# ---------------------------------------------------------------------------


def test_roundtrip_catches_json_field_drop(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If spec_to_json silently drops ``self_concerns`` from the JSON
    payload, the round-tripped Spec will have an empty ``self_concerns``
    list — the deep-equal check must surface it as the very first diff so
    the rewriter knows which field regressed."""
    spec = _baseline_spec()
    # Sanity precondition for the test itself.
    assert spec.self_concerns, "baseline must have self_concerns for this test"

    real_spec_to_json = md_json_bridge.spec_to_json

    def lossy_spec_to_json(spec_arg: Spec) -> str:
        import json as _json

        data = spec_arg.model_dump(mode="json")
        # Simulate the failure mode where the writer's segment-merge step
        # silently dropped this field instead of carrying it through.
        data["self_concerns"] = []
        return _json.dumps(data, ensure_ascii=False, indent=2)

    monkeypatch.setattr(md_json_bridge, "spec_to_json", lossy_spec_to_json)

    with pytest.raises(ValueError) as exc_info:
        assert_spec_roundtrip_consistent(spec)

    msg = str(exc_info.value)
    assert "roundtrip" in msg.lower()
    # Field path MUST appear in the error so an operator can fix the bridge
    # without re-running the validator with debug prints.
    assert "self_concerns" in msg

    # And the function recovers fully once the lossy patch is undone — i.e.
    # there's no hidden state carried across calls.
    monkeypatch.setattr(md_json_bridge, "spec_to_json", real_spec_to_json)
    assert_spec_roundtrip_consistent(spec)


# ---------------------------------------------------------------------------
# 4. Footer tolerance — the writer's auto-generated footer line must NOT
#    register as drift.
# ---------------------------------------------------------------------------


def test_roundtrip_tolerates_writer_footer() -> None:
    """``spec_to_markdown`` always appends a ``_Generated by DevLoop ..._``
    footer. That line is intentionally non-normative — it carries writer/
    reviewer model names + iteration count that are NOT round-tripped
    through json (writer_model and friends ARE in metadata, but the line
    *itself* is decorative). Neither defense may flag it as drift."""
    spec = _baseline_spec()
    md = spec_to_markdown(spec)

    # Precondition: the footer is actually rendered.
    assert "_Generated by DevLoop" in md, (
        "footer line missing — _baseline_spec or spec_to_markdown changed"
    )
    assert "writer=claude" in md
    assert "reviewer=gpt" in md
    assert "iterations=2" in md

    # find_md_only_content uses ``## ...`` H2-section scanning; the footer
    # is a horizontal-rule + italic line, NOT a section, so it must not be
    # flagged. (Sanity-checks the documented exclusion in the module docstring.)
    assert find_md_only_content(spec) == []

    # And the full roundtrip assertion must pass — the footer is byte-stable
    # across renders because all three of writer/reviewer/iterations come
    # from metadata, which IS in the json payload.
    assert_spec_roundtrip_consistent(spec)


# ---------------------------------------------------------------------------
# 5. Unicode survival — emoji + CJK must survive roundtrip byte-for-byte.
# ---------------------------------------------------------------------------


def test_roundtrip_on_spec_with_unicode_in_descriptions() -> None:
    """Emoji and CJK characters in normative fields must roundtrip cleanly.
    spec_to_json uses ``ensure_ascii=False`` for exactly this reason — if a
    refactor flipped that flag, the JSON payload would carry ``\\uXXXX``
    escapes, the round-tripped Spec would have literal ``\\uXXXX`` strings,
    and the markdown render would diverge from the original. This test is
    the canary for that regression."""
    spec = Spec(
        metadata=SpecMetadata(
            feature_id="unicode-feature-🌟",
            title="国际化 / Internationalization 🌍",
        ),
        summary="支持 multi-byte characters: 中文, 日本語, 한국어, العربية, emoji 🚀✨.",
        user_stories=[
            UserStory(
                id="US-1",
                priority=Priority.P1,
                title="ユーザーが日本語でコメントできる 💬",
                description=(
                    "Logged-in 用户 should be able to 投稿 a 评论 with full "
                    "Unicode support: 漢字, ひらがな, カタカナ, emoji 😀🎉."
                ),
                acceptance=[
                    AcceptanceScenario(
                        given="I am 已登录",
                        when="I 提交 a comment with 🌟 emoji",
                        then="the comment 显示 with all characters intact ✅",
                    )
                ],
            )
        ],
        functional_requirements=[
            FunctionalRequirement(
                id="FR-001",
                text=(
                    "Comments must support U+1F600 and CJK Unified Ideographs "
                    "(中文/日本語/한국어) without mojibake."
                ),
                requirement_type="functional",
            )
        ],
        success_criteria=[
            SuccessCriterion(
                id="SC-001",
                text="Zero mojibake in 100% of unicode test corpus.",
                metric="character-equality count",
                threshold="100% byte-for-byte preserved",
            )
        ],
    )

    # Roundtrip must not raise. This implicitly verifies BOTH the json
    # deep-equal AND the markdown byte-equality flanks of the assertion.
    assert_spec_roundtrip_consistent(spec)

    # And the rendered markdown literally contains the unicode (no \uXXXX
    # escaping in the human-facing artifact).
    md = spec_to_markdown(spec)
    assert "中文" in md
    assert "日本語" in md
    assert "🚀" in md
    # And the JSON payload too — ensure_ascii=False guarantees this.
    js = spec_to_json(spec)
    assert "中文" in js
    assert "🚀" in js
    # Defensive: no accidental \uXXXX escaping leaked in.
    assert "\\u4e2d" not in js, "CJK escaped to \\uXXXX — ensure_ascii flag flipped?"
    assert "\\ud83d" not in js, "emoji surrogate escaped — ensure_ascii flag flipped?"


# ---------------------------------------------------------------------------
# 6. Edge case — empty user_stories (and most other optional sections empty).
# ---------------------------------------------------------------------------


def test_roundtrip_on_spec_with_no_user_stories() -> None:
    """A minimal spec — only metadata + summary, every list field default
    empty — must roundtrip cleanly. The rendered markdown skips every
    empty section (``if spec.user_stories:`` etc.), and the JSON deep-equal
    must still match because empty lists roundtrip to empty lists."""
    spec = Spec(
        metadata=SpecMetadata(
            feature_id="minimal-spec",
            title="Minimal Spec — only the summary is populated",
        ),
        summary="A minimal feature spec with no user stories or requirements.",
        # All collection fields explicitly empty — exercising the edge case.
        user_stories=[],
        functional_requirements=[],
        success_criteria=[],
        key_entities=[],
        edge_cases=[],
        assumptions=[],
        out_of_scope=[],
        self_concerns=[],
        needs_clarification=[],
    )

    # Sanity preconditions.
    assert spec.user_stories == []
    assert spec.functional_requirements == []

    # No drift, no unmapped sections.
    assert_spec_roundtrip_consistent(spec)
    assert find_md_only_content(spec) == []

    # Rendered markdown skips every empty section but still has the title +
    # summary (proving the renderer didn't crash on emptiness either).
    md = spec_to_markdown(spec)
    assert "# Feature Specification: Minimal Spec" in md
    assert "## Summary" in md
    # And NONE of the optional sections leaked through.
    assert "## User Scenarios" not in md
    assert "## Requirements" not in md
    assert "## Success Criteria" not in md
    assert "## Self-Concerns" not in md


if __name__ == "__main__":  # pragma: no cover
    pytest.main([__file__, "-v"])
